### ISSUE TITLE
Need maintainer ?

### ISSUE THREAD

**Issue by Celemo** [YunoHost-Apps/pterodactyl_ynh#22]
Hi,
It's look like the package has not been updated since 1 year and seems unmaintained. 

Do you need any maintainer to continue your work ? I want to start maintaining some apps for Yunohost and I think Pterodactyl is a great start because I installed this panel so many times that I know perfectly how it works.

I already forked this repo and tested some fixes and upgrades on the app CI ( [![Build Status](https://ci-apps-dev.yunohost.org/jenkins/buildStatus/icon?job=pterodactyl_ynh (aeris))](https://ci-apps-dev.yunohost.org/jenkins/job/pterodactyl_ynh%20(aeris)/) ) (for now it didn't work but I'm on the way ! 😅)

So... Do you still maintain the package ?
If not, can I be the new maintainer of this app ?

Thanks for reading,
Aeris 🇫🇷

**Comment by arcdigital** [comment]
Hey, I'm one of the devs for Pterodactyl. I'm willing to maintain this.

**Comment by Celemo** [comment]
Solved -> https://github.com/YunoHost/apps/pull/889
