### ISSUE TITLE
Pterodactyl_ynh not working after install

### ISSUE THREAD

**Issue by tmdg2** [YunoHost-Apps/pterodactyl_ynh#37]
install log yunohost 
https://paste.yunohost.org/raw/zamugacele

pterodactyl.pushedgaming.de-access.log

[pterodactyl.pushedgaming.de-access.log](https://github.com/YunoHost-Apps/pterodactyl_ynh/files/11115576/pterodactyl.pushedgaming.de-access.log)

80.110.214.237 - dany [30/Mar/2023:21:37:08 +0200] "GET /pterodactyl/ HTTP/2.0" 404 16 "https://doamin/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
80.110.214.237 - - [30/Mar/2023:21:37:08 +0200] "GET /favicon.ico HTTP/2.0" 302 138 "https://sub.doamin/pterodactyl/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
80.110.214.237 - dany [30/Mar/2023:21:44:26 +0200] "GET /pterodactyl/ HTTP/2.0" 404 16 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
80.110.214.237 - - [30/Mar/2023:21:44:26 +0200] "GET /favicon.ico HTTP/2.0" 302 138 "https://sub.doamin/pterodactyl/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"

pterodactyl.pushedgaming.de-error.log

[pterodactyl.pushedgaming.de-access.log](https://github.com/YunoHost-Apps/pterodactyl_ynh/files/11115593/pterodactyl.pushedgaming.de-access.log)

2023/03/30 21:37:08 [error] 205796#205796: *108 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 80.110.214.237, server: sub.doamin, request: "GET /pterodactyl/ HTTP/2.0", upstream: "fastcgi://unix:/run/php/php8.0-fpm-pterodactyl.sock:", host: "sub.doamin", referrer: "https://doamin/"
2023/03/30 21:44:26 [error] 205796#205796: *113 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 80.110.214.237, server: sub.doamin, request: "GET /pterodactyl/ HTTP/2.0", upstream: "fastcgi://unix:/run/php/php8.0-fpm-pterodactyl.sock:", host: "sub.doamin"

![image](https://user-images.githubusercontent.com/11587417/228949435-47557af5-7fb7-4fe7-9530-a1019645c47c.png)

**Comment by Aeris1One** [comment]
Hey,
This package is really outdated, and marked as non-working and level 0 on apps directory, why did you try to install it ?

We are on our way in #36 to upgrade it and make it working again, by the time it should be considered a broken legacy package which isn't working at all.

**Comment by woLiii** [comment]
Hello, 
I tried with https://github.com/YunoHost-Apps/pterodactyl_ynh/tree/fix and i can tell you it works for me.
Just need to Upgrade to newest version.

But one thing is broken.
If you installed a Server, you cant use there File Browser for Editing etc.
